- name: create directory for jharm
  file:
    path: /opt/jharm/
    state: directory

- name: clone JHarm repository
  git:
    clone: yes
    dest: "/opt/jharm/"
    repo: "https://github.com/lukasbalazik123/jharm.git"

- name: install pip3
  package:
    name: python3-pip

- name: install pyzmq
  pip:
    name: pyzmq

- name: install syslog-ng
  package:
    name: syslog-ng

- name: copy syslog-ng configuration to /etc/syslog-ng/conf.d/
  copy:
    src: "/opt/jharm/configurations/syslog-ng/conf.d/03jh_{{ item.name }}.conf"
    dest: "/etc/syslog-ng/conf.d/"
    remote_src: true
  with_items: "{{ enabled_configs }}"

- name: create startup daemons
  template:
    src: "daemon.conf"
    dest: "/etc/init.d/jh_{{ item.name }}"
  with_items: "{{ enabled_configs }}"
